package com.example.Notes.model;

import jakarta.persistence.*;
import java.util.Set;

@Entity //Indicates that this class is a JPA entity(So that it can be mapped to a database table)
public class Category {

    @Id //Primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Auto increment strategy(ID will be generated by the database)
    private Long id; //Space for large no.(64 bits) , For Spring Data JPA ,integrates well with database auto increment
    private String name;  // The name of the category

    // One category can have multiple notes (One to Many relationship)
    @OneToMany(mappedBy = "category") //Foreign key is in Note entity
    private Set<Note> notes; //set to hold multiple notes

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<Note> getNotes() {
        return notes;
    }

    public void setNotes(Set<Note> notes) {
        this.notes = notes;
    }
}
