package com.example.Notes.model;

import jakarta.persistence.*;

import java.util.Collection;
import java.util.List;
import java.util.Set;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

@Entity
public class User implements UserDetails{

    @Id //Primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Auto increment strategy(ID will be generated by the database)

    private Long id;
    private String username;
    private String password;

    @OneToMany(mappedBy = "user") //Foreign key is in Note entity(Many side)
    private Set<Note> notes;

    //Default constructor   
    public User(){}

    //Constructors for creating User with username and password
    public User(String username, String password){
        this.username = username;
        this.password = password;
    }

    //Implementing method from UserDetails interface
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities(){ //Any subclass of GrantedAuthority() -for future flexibility(Can use any class that implements GrantAuthority)
        return List.of(() -> "ROLE_USER"); //Returning a list because - In future it might have many roles
    }

    @Override
    public String getPassword(){
        return password;
    }

    @Override  
    public String getUsername(){
        return username;
    }

    //Getter and Setters
    public Long getId(){
        return id;
    }

    public Set<Note> getNotes(){
        return notes;
    }

    public void setNotes(Set<Note> notes){
        this.notes  = notes;
    }

    //For signup
    public void setUsername(String username){
        this.username = username;
    }

    public void setPassword(String password){
        this.password = password;
    }

}

    
    














